apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: spring-runner-deployment 
  janus-idp.io/tekton: spring-runner-deployment
  backstage.io/kubernetes-id: spring-runner-deployment
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: spring-runner-deployment
resources:
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml