apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: spring-runner-deployment-gitops-repository
spec:
  url: https://github.com/lucarval-rhtap/spring-runner-deployment-gitops